// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/jwt/generator.go
//
// Generated by this command:
//
//	mockgen -package mock -destination=test/mock/jwt_generator_mock.go -source=pkg/jwt/generator.go
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	time "time"

	jwt "github.com/solutionchallenge/ondaum-server/pkg/jwt"
	gomock "go.uber.org/mock/gomock"
)

// MockGenerator is a mock of Generator interface.
type MockGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockGeneratorMockRecorder
	isgomock struct{}
}

// MockGeneratorMockRecorder is the mock recorder for MockGenerator.
type MockGeneratorMockRecorder struct {
	mock *MockGenerator
}

// NewMockGenerator creates a new mock instance.
func NewMockGenerator(ctrl *gomock.Controller) *MockGenerator {
	mock := &MockGenerator{ctrl: ctrl}
	mock.recorder = &MockGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerator) EXPECT() *MockGeneratorMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *MockGenerator) GenerateToken(typ jwt.Type, value string, metadata map[string]any, duration time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", typ, value, metadata, duration)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockGeneratorMockRecorder) GenerateToken(typ, value, metadata, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockGenerator)(nil).GenerateToken), typ, value, metadata, duration)
}

// GenerateTokenPair mocks base method.
func (m *MockGenerator) GenerateTokenPair(value string, metadata ...map[string]any) (*jwt.TokenPair, error) {
	m.ctrl.T.Helper()
	varargs := []any{value}
	for _, a := range metadata {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GenerateTokenPair", varargs...)
	ret0, _ := ret[0].(*jwt.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTokenPair indicates an expected call of GenerateTokenPair.
func (mr *MockGeneratorMockRecorder) GenerateTokenPair(value any, metadata ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{value}, metadata...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokenPair", reflect.TypeOf((*MockGenerator)(nil).GenerateTokenPair), varargs...)
}

// GetTokenType mocks base method.
func (m *MockGenerator) GetTokenType(tokenString string) (jwt.Type, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenType", tokenString)
	ret0, _ := ret[0].(jwt.Type)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenType indicates an expected call of GetTokenType.
func (mr *MockGeneratorMockRecorder) GetTokenType(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenType", reflect.TypeOf((*MockGenerator)(nil).GetTokenType), tokenString)
}

// RefreshTokenPair mocks base method.
func (m *MockGenerator) RefreshTokenPair(refreshTokenString string) (*jwt.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTokenPair", refreshTokenString)
	ret0, _ := ret[0].(*jwt.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshTokenPair indicates an expected call of RefreshTokenPair.
func (mr *MockGeneratorMockRecorder) RefreshTokenPair(refreshTokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTokenPair", reflect.TypeOf((*MockGenerator)(nil).RefreshTokenPair), refreshTokenString)
}

// UnpackToken mocks base method.
func (m *MockGenerator) UnpackToken(tokenString string) (*jwt.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpackToken", tokenString)
	ret0, _ := ret[0].(*jwt.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnpackToken indicates an expected call of UnpackToken.
func (mr *MockGeneratorMockRecorder) UnpackToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpackToken", reflect.TypeOf((*MockGenerator)(nil).UnpackToken), tokenString)
}
