verbose: true
http:
  host: "0.0.0.0"
  port: 8080
  buffer:
    read: 4096
    write: 4096
  limit:
    payload: 1024
    concurrency: 100
  timeout:
    read: "10s"
    write: "10s"
    idle: "10s"
    shutdown: "10s"
database:
  kind: "memdb"
  host: "localhost"
  port: 0
  database: "ondaum"
  user: 
  password:
migration:
  enabled: true
oauth:
  google:
    enabled: true
    client_id: 
    client_secret: 
    default_redirection: "http://localhost:8080/api/v1/_debug/oauth"
    allowed_redirections:
      - "http://localhost/oauth/google"
      - "http://localhost:8080/oauth/google"
      - "http://localhost:3000/oauth/google"
      - "http://localhost:5173/oauth/google"
      - "http://localhost:5174/oauth/google"
      - "http://localhost:8080/api/v1/_debug/oauth"
      - "https://ondaum.revimal.me/oauth/google"
jwt:
  secret_key:
  access_expire: 86400
  refresh_expire: 604800
future:
  enabled: true
  schedule_cycle: 5m
  delete_after_completion: false
llm:
  gemini:
    enabled: true
    api_key:
    llm_model: gemini-1.5-pro
    embedding_model: text-embedding-001
    response_format: application/json
    prepared_prompts:
      - identifier: interactive_chat
        prompt_type: system_instruction
        prompt_file: resource/llm/prompt/interactive-chat-prompt-v1.md
      - identifier: summary_chat
        prompt_type: action_prompt
        prompt_file: resource/llm/prompt/summary-chat-prompt-v1.md
        attachment_file: resource/llm/attachment/counseling-psychology-101.pdf
        attachment_mime: application/pdf
        attachment_ttl: 1h
    redaction_threshold:
      harrasement: low
      hate_speech: medium
      sexually_explicit: high
      dangerous_content: medium
      civic_integrity: none
