verbose: true
http:
  host: "0.0.0.0"
  port: 8080
  buffer:
    read: 4096
    write: 4096
  limit:
    payload: 1024
    concurrency: 100
  timeout:
    read: "10s"
    write: "10s"
    idle: "10s"
    shutdown: "10s"
database:
  kind: "memdb"
  host: "localhost"
  port: 0
  database: "ondaum"
  user: 
  password:
migration:
  enabled: true
oauth:
  google:
    enabled: true
    client_id: 
    client_secret: 
    default_redirection: "http://localhost:5173/oauth/google"
    allowed_redirections:
      - "http://localhost/oauth/google"
      - "http://localhost:8080/oauth/google"
      - "http://localhost:3000/oauth/google"
      - "http://localhost:5173/oauth/google"
      - "http://localhost:8080/_debug/oauth"
      - "https://ondaum.revimal.me/oauth/google"
jwt:
  secret_key:
  access_expire: 3600
  refresh_expire: 604800

