// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/_schema/supported-emotions": {
            "get": {
                "description": "List supported emotions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schema"
                ],
                "summary": "List supported emotions",
                "operationId": "ListSupportedEmotion",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/common.Emotion"
                            }
                        }
                    }
                }
            }
        },
        "/_schema/supported-features": {
            "get": {
                "description": "List supported features",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schema"
                ],
                "summary": "List supported features",
                "operationId": "ListSupportedFeature",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/common.Feature"
                            }
                        }
                    }
                }
            }
        },
        "/_schema/supported-diagnoses": {
            "get": {
                "description": "List supported tests",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schema"
                ],
                "summary": "List supported tests",
                "operationId": "ListSupportedTest",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/common.Diagnosis"
                            }
                        }
                    }
                }
            }
        },
        "/_ws/chat": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Connect Chat Websocket. Reference the notion page for more information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Connect Chat Websocket",
                "operationId": "ConnectChatWebsocket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Websocket Session ID (optional; if not provided, the server will use the most recent non-archived conversation or create a new one if none exists)",
                        "name": "session_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/websocket.ResponseWrapper"
                        }
                    },
                    "426": {
                        "description": "Upgrade Required",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    }
                }
            }
        },
        "/chat/:session_id": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get chat with histories and summary",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Get chat",
                "operationId": "GetChat",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/chat.ChatWithSummaryAndHistoriesDTO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    }
                }
            }
        },
        "/chat/:session_id/archive": {
            "post": {
                "description": "Archive a chat to prevent it from being accessed again and allow to summarize it.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Archive a chat",
                "operationId": "ArchiveChat",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/chat.ArchiveChatHandlerResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    }
                }
            }
        },
        "/chat/:session_id/summary": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get summary of the chat",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Get summary",
                "operationId": "GetSummary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/chat.SummaryDTO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    }
                }
            }
        },
        "/chats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List chats with summaries",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "List chats",
                "operationId": "ListChat",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/chat.ChatWithSummaryDTO"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    }
                }
            }
        },
        "/chats/:session_id/summary": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create or update chat summary and return the created/updated chat summary",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Create or update chat summary",
                "operationId": "UpsertChatSummary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/chat.UpsertChatSummaryHandlerResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    }
                }
            }
        },
        "/diagnosis/:diagnosis_id": {
            "get": {
                "description": "Get diagnosis paper as JSON format",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Get diagnosis paper",
                "operationId": "GetDiagnosisPaper",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Diagnosis ID",
                        "name": "diagnosis_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.DiagnosisPaper"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    }
                }
            }
        },
        "/oauth/google/auth": {
            "post": {
                "description": "Receives the authorization code (obtained from Google OAuth) and exchanges it for access and refresh tokens.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oauth"
                ],
                "summary": "Exchange Google OAuth Code for Tokens",
                "operationId": "ExchangeGoogleOAuthCode",
                "parameters": [
                    {
                        "description": "Payload containing the authorization code received from Google OAuth",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/oauth.AuthGoogleHandlerRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Redirect URI (optional; the client's callback URL where Google was redirect with the code)",
                        "name": "redirect",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/oauth.AuthGoogleHandlerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    }
                }
            }
        },
        "/oauth/google/start": {
            "get": {
                "description": "Returns the Google OAuth authorization URL, which includes the specified redirect URI (the URL where Google will send the authorization code after login).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oauth"
                ],
                "summary": "Get Google OAuth Authorization URL",
                "operationId": "StartGoogleOAuth",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Redirect URI (the client's callback URL where Google will redirect with the code)",
                        "name": "redirect",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/oauth.StartGoogleHandlerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    }
                }
            }
        },
        "/user/addition": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates or creates the user's additional information including concerns and emotions.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Update or Create User Additional Information",
                "operationId": "UpsertUserAddition",
                "parameters": [
                    {
                        "description": "User additional information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UpsertUserAdditionHandlerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.UpsertUserAdditionHandlerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    }
                }
            }
        },
        "/user/privacy": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates or creates the user's privacy information including gender and birthday.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Update or Create User Privacy Information",
                "operationId": "UpsertUserPrivacy",
                "parameters": [
                    {
                        "description": "User privacy information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UpsertUserPrivacyHandlerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.UpsertUserPrivacyHandlerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    }
                }
            }
        },
        "/user/self": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the authenticated user's profile, including basic information and optional onboarding data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get Current Authenticated User Profile",
                "operationId": "GetSelfUser",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.SimplifiedUserDTO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "chat.ArchiveChatHandlerResponse": {
            "type": "object",
            "properties": {
                "finished": {
                    "type": "boolean"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "chat.ChatWithSummaryAndHistoriesDTO": {
            "type": "object",
            "properties": {
                "histories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/chat.HistoryDTO"
                    }
                },
                "id": {
                    "type": "string"
                },
                "is_archived": {
                    "type": "boolean"
                },
                "is_finished": {
                    "type": "boolean"
                },
                "session_id": {
                    "type": "string"
                },
                "started_date": {
                    "type": "string"
                },
                "summary": {
                    "$ref": "#/definitions/chat.SummaryDTO"
                },
                "user_id": {
                    "type": "string"
                },
                "user_timezone": {
                    "type": "string"
                }
            }
        },
        "chat.ChatWithSummaryDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "is_archived": {
                    "type": "boolean"
                },
                "is_finished": {
                    "type": "boolean"
                },
                "session_id": {
                    "type": "string"
                },
                "started_date": {
                    "type": "string"
                },
                "summary": {
                    "$ref": "#/definitions/chat.SummaryDTO"
                },
                "user_id": {
                    "type": "string"
                },
                "user_timezone": {
                    "type": "string"
                }
            }
        },
        "chat.HistoryDTO": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "metadata": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "role": {
                    "type": "string"
                },
                "when": {
                    "type": "string"
                }
            }
        },
        "chat.SummaryDTO": {
            "type": "object",
            "properties": {
                "emotions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/common.EmotionRate"
                    }
                },
                "keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "text": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "chat.UpsertChatSummaryHandlerResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "boolean"
                },
                "returning": {
                    "$ref": "#/definitions/chat.SummaryDTO"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "common.Emotion": {
            "type": "string",
            "enum": [
                "joy",
                "sadness",
                "anger",
                "surprise",
                "fear",
                "disgust",
                "neutral"
            ],
            "x-enum-varnames": [
                "EmotionJoy",
                "EmotionSadness",
                "EmotionAnger",
                "EmotionSurprise",
                "EmotionFear",
                "EmotionDisgust",
                "EmotionNeutral"
            ]
        },
        "common.EmotionRate": {
            "type": "object",
            "properties": {
                "emotion": {
                    "$ref": "#/definitions/common.Emotion"
                },
                "rate": {
                    "type": "number"
                }
            }
        },
        "common.Feature": {
            "type": "string",
            "enum": [
                "escalate_crisis",
                "suggest_test_phq9",
                "suggest_test_gad7",
                "suggest_test_pss",
                "end_conversation"
            ],
            "x-enum-varnames": [
                "FeatureEscalateCrisis",
                "FeatureSuggestTestPHQ9",
                "FeatureSuggestTestGAD7",
                "FeatureSuggestTestPSS",
                "FeatureEndConversation"
            ]
        },
        "common.Diagnosis": {
            "type": "string",
            "enum": [
                "phq-9",
                "gad-7",
                "pss"
            ],
            "x-enum-varnames": [
                "DiagnosisPHQ9",
                "DiagnosisGAD7",
                "DiagnosisPSS"
            ]
        },
        "common.DiagnosisAnswer": {
            "type": "object",
            "properties": {
                "score": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "common.DiagnosisPaper": {
            "type": "object",
            "properties": {
                "guides": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/common.DiagnosisQuestion"
                    }
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/common.DiagnosisResult"
                    }
                },
                "scoring": {
                    "$ref": "#/definitions/common.DiagnosisScoring"
                }
            }
        },
        "common.DiagnosisQuestion": {
            "type": "object",
            "properties": {
                "answers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/common.DiagnosisAnswer"
                    }
                },
                "index": {
                    "type": "integer"
                },
                "question": {
                    "type": "string"
                }
            }
        },
        "common.DiagnosisResult": {
            "type": "object",
            "properties": {
                "critical": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "max": {
                    "type": "integer"
                },
                "min": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "common.DiagnosisScoring": {
            "type": "object",
            "properties": {
                "max": {
                    "type": "integer"
                },
                "min": {
                    "type": "integer"
                }
            }
        },
        "http.Error": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "oauth.AuthGoogleHandlerRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "oauth.AuthGoogleHandlerResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "oauth.StartGoogleHandlerResponse": {
            "type": "object",
            "properties": {
                "auth_url": {
                    "type": "string"
                }
            }
        },
        "user.SimplifiedAdditionDTO": {
            "type": "object",
            "properties": {
                "concerns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "emotions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/common.Emotion"
                    }
                }
            }
        },
        "user.SimplifiedPrivacyDTO": {
            "type": "object",
            "properties": {
                "birthday": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                }
            }
        },
        "user.SimplifiedUserDTO": {
            "type": "object",
            "properties": {
                "addition": {
                    "$ref": "#/definitions/user.SimplifiedAdditionDTO"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "privacy": {
                    "$ref": "#/definitions/user.SimplifiedPrivacyDTO"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "user.UpsertUserAdditionHandlerRequest": {
            "type": "object",
            "properties": {
                "concerns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "emotions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/common.Emotion"
                    }
                }
            }
        },
        "user.UpsertUserAdditionHandlerResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "boolean"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "user.UpsertUserPrivacyHandlerRequest": {
            "type": "object",
            "properties": {
                "birthday": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                }
            }
        },
        "user.UpsertUserPrivacyHandlerResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "boolean"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "websocket.Action": {
            "type": "string",
            "enum": [
                "noop",
                "reject",
                "data",
                "notify"
            ],
            "x-enum-varnames": [
                "PredefinedActionNoop",
                "PredefinedActionReject",
                "PredefinedActionData",
                "PredefinedActionNotify"
            ]
        },
        "websocket.ResponseWrapper": {
            "type": "object",
            "properties": {
                "action": {
                    "$ref": "#/definitions/websocket.Action"
                },
                "message_id": {
                    "type": "string"
                },
                "payload": {},
                "session_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "ondaum.revimal.me",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Ondaum API",
	Description:      "This is a API server for Ondaum",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
