name: Pull Request Check

on:
  pull_request:

jobs:
  check-swagger-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate Swagger docs
        run: swag init

      - name: Check for Swagger doc changes
        run: |
          if [ -n "$(git status --porcelain docs/)" ]; then
            echo "Swagger documentation has changed. Please run 'swag init' locally and commit the changes."
            git diff docs/
            exit 1
          fi 